const C=document.querySelector("#g"),X=C.getContext("2d"),MI=document.querySelector("#mini"),MX=MI.getContext("2d"),$=s=>document.querySelector(s);const T=14,MW=120,MH=80,WW=MW*T,WH=MH*T;let maps=[],M,p,E=[],L=[],V=[],S=[],G=[],F=[],last=0,move={x:0,y:0},aim={x:1,y:0},hold=false,weapon="rifle",audio;
const gun={rifle:{mag:30,d:34,r:.17,range:370},smg:{mag:45,d:20,r:.09,range:270},shotgun:{mag:8,d:78,r:.62,range:150}};
fetch("levels.json").then(r=>r.json()).then(d=>{maps=d.maps;load(+localStorage.getItem("sombra_sector")||1);navigator.serviceWorker?.register("sw.js");requestAnimationFrame(loop)});
function P(o){return{x:(o.x+.5)*T,y:(o.y+.5)*T}}function pass(x,y){let a=Math.floor(x/T),b=Math.floor(y/T);return a>=0&&b>=0&&a<MW&&b<MH&&(M.grid[b][a]=="."||M.grid[b][a]=="~")}function snd(f,d=.05){try{audio=audio||new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
function load(n){M=maps[Math.max(0,Math.min(29,n-1))];let s=P(M.start);p={x:s.x,y:s.y,hp:100,ammo:30,nades:3,armor:0,cd:0,med:0,car:false,kills:0};E=[];M.squads.forEach(q=>q.members.forEach(m=>{let z=P(m);E.push({x:z.x,y:z.y,hp:100,alive:true,alert:false,cd:Math.random(),sq:q.id})}));L=M.loot.map((l,i)=>({...P(l),type:l.type,got:false,id:i}));V=M.vehicles.map(P);S=[];G=[];F=[];last=0;zoneT=120;zoneR=650;weapon="rifle";hold=false;$("#hp").textContent=100;$("#alive").textContent=E.length+1;$("#kills").textContent=0;$("#nads").textContent=3;$("#armor").textContent="NO";document.querySelectorAll(".gun").forEach((b,i)=>b.classList.toggle("sel",i===0));$("#modal").style.display="none";snd(250,.07)}
function stepPlayer(dt){let sp=p.car?105:60,nx=p.x+move.x*sp*dt,ny=p.y+move.y*sp*dt;if(pass(nx,p.y))p.x=nx;if(pass(p.x,ny))p.y=ny}
function fire(){let q=gun[weapon];if(p.cd>0||p.ammo<=0)return;p.cd=q.r;p.ammo--;document.querySelector(".gun.sel span").textContent=p.ammo;snd(180);S.push({x:p.x,y:p.y,dx:aim.x,dy:aim.y,range:q.range,d:q.d,enemy:false})}
function grenade(){if(!p.nades)return;p.nades--;$("#nads").textContent=p.nades;G.push({x:p.x,y:p.y,tx:p.x+aim.x*170,ty:p.y+aim.y*170,t:0});snd(100,.1)}
function heal(){if(p.med||p.hp>=100)return;p.med=1;snd(520,.08)}
function updateHeal(dt){if(p.med){p.hp=Math.min(100,p.hp+24*dt);$("#hp").textContent=Math.round(p.hp);if(p.hp>=100){p.med=0;snd(760)}}}
function ai(e,dt){if(!e.alive)return;let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy);if(d<300){e.alert=true;let m=d||1;if(d>100&&pass(e.x+dx/m*10,e.y+dy/m*10)){e.x+=dx/m*18*dt;e.y+=dy/m*18*dt}e.cd-=dt;if(d<250&&e.cd<=0){e.cd=1+Math.random()*.6;S.push({x:e.x,y:e.y,dx:dx/m,dy:dy/m,range:290,d:7,enemy:true})}}}
function shots(dt){for(let s of S){s.x+=s.dx*720*dt;s.y+=s.dy*720*dt;s.range-=720*dt;if(s.range<=0||!pass(s.x,s.y)){s.dead=true;continue}if(s.enemy){if(Math.hypot(s.x-p.x,s.y-p.y)<11){p.hp=Math.max(0,p.hp-(p.armor?4:7));$("#hp").textContent=Math.round(p.hp);s.dead=true;if(p.hp<=0)end(false)}}else for(let e of E)if(e.alive&&Math.hypot(s.x-e.x,s.y-e.y)<13){e.hp-=s.d;s.dead=true;if(e.hp<=0){e.alive=false;p.kills++;$("#kills").textContent=p.kills;F.push({x:e.x,y:e.y,t:0});snd(80,.08)}break}}S=S.filter(s=>!s.dead)}
function gren(dt){for(let g of G){g.t+=dt;if(g.t>.55){for(let e of E)if(e.alive&&Math.hypot(e.x-g.tx,e.y-g.ty)<82){e.hp-=95;if(e.hp<=0){e.alive=false;p.kills++;$("#kills").textContent=p.kills}}F.push({x:g.tx,y:g.ty,t:0,boom:true});snd(60,.15);g.dead=true}}G=G.filter(g=>!g.dead)}
function loot(){let l=L.find(l=>!l.got&&Math.hypot(l.x-p.x,l.y-p.y)<25);if(!l)return;l.got=true;snd(700);if(l.type==="ammo")p.ammo=Math.min(90,p.ammo+20);if(l.type==="armor"){p.armor=1;$("#armor").textContent="SI"}if(l.type==="medkit")p.hp=Math.min(100,p.hp+35);if(l.type==="grenade"){p.nades=Math.min(6,p.nades+2);$("#nads").textContent=p.nades}if(gun[l.type]){weapon=l.type;p.ammo=gun[weapon].mag;document.querySelectorAll(".gun").forEach(b=>b.classList.toggle("sel",b.dataset.w===weapon))}document.querySelector(".gun.sel span").textContent=p.ammo}
function vehicle(){let v=V.find(v=>Math.hypot(v.x-p.x,v.y-p.y)<30);if(v){p.car=!p.car;snd(p.car?330:180)}}
function zone(dt){zoneT-=dt;if(zoneT<=0){zoneT=120;zoneR=Math.max(220,zoneR-65)}let d=Math.hypot(p.x-WW/2,p.y-WH/2);if(d>zoneR){p.hp=Math.max(0,p.hp-4*dt);$("#hp").textContent=Math.round(p.hp);if(p.hp<=0)end(false)}$("#timer").textContent=`${String(Math.ceil(zoneT/60)).padStart(2,"0")}:${String(Math.ceil(zoneT)%60).padStart(2,"0")}`}
function objective(){let o=P(M.objective),e=P(M.extract);if(!M.done&&Math.hypot(p.x-o.x,p.y-o.y)<30){M.done=true;snd(800,.12);$("#zone").textContent="🎯 OBJETIVO COMPLETADO"}if(M.done&&Math.hypot(p.x-e.x,p.y-e.y)<32)end(true)}
function end(ok){if(document.querySelector("#modal").style.display==="grid")return;$("#modal").style.display="grid";$("#title").textContent=ok?"VICTORIA":"ELIMINADO";$("#msg").textContent=ok?`${M.name} · ${p.kills} bajas · extracción asegurada.`:"Has caído en combate.";if(ok&&M.id<30)localStorage.setItem("sombra_sector",M.id+1);snd(ok?900:70,.2)}
function soldier(x,y,enemy,ax,ay){X.save();X.translate(x,y);X.rotate(Math.atan2(ay||0,ax||1));X.fillStyle=enemy?"#a94753":"#4d8469";X.fillRect(-8,-7,16,14);X.fillStyle=enemy?"#d7a98d":"#d7b08d";X.beginPath();X.arc(0,-9,5,0,7);X.fill();X.fillStyle="#222b24";X.fillRect(-5,-12,10,5);X.fillStyle="#161c18";X.fillRect(5,-2,14,4);X.restore()}
function draw(){X.clearRect(0,0,C.width,C.height);let vw=C.width/1.25,vh=C.height/1.25,cx=Math.max(0,Math.min(p.x-vw/2,WW-vw)),cy=Math.max(0,Math.min(p.y-vh/2,WH-vh));X.save();X.scale(1.25,1.25);X.translate(-cx,-cy);
for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){let c=M.grid[y][x];X.fillStyle=c=="#"?"#766653":c=="~"?"#4d909c":((x+y)%2?"#708a51":"#789258");X.fillRect(x*T,y*T,T,T)}
for(let a of M.props){let x=(a.x+.5)*T,y=(a.y+.5)*T;if(a.type=="tree"){X.fillStyle="#315d35";X.beginPath();X.arc(x,y-4,10,0,7);X.fill();X.fillStyle="#60452d";X.fillRect(x-2,y,4,9)}else{X.fillStyle="#707a6e";X.beginPath();X.ellipse(x,y,7,5,0,0,7);X.fill()}}
for(let b of M.buildings){X.fillStyle="#a97956";X.fillRect(b.x*T,b.y*T,b.w*T,b.h*T);X.strokeStyle="#e1c8a7";X.lineWidth=2;X.strokeRect(b.x*T+1,b.y*T+1,b.w*T-2,b.h*T-2);X.fillStyle="#d8c39e";X.fillRect((b.x+2)*T,(b.y+2)*T,(b.w-4)*T,(b.h-4)*T);X.strokeStyle="#92775f";X.strokeRect((b.x+2)*T,(b.y+2)*T,(b.w-4)*T,(b.h-4)*T);X.fillStyle="#8b654d";X.fillRect((b.x+b.w/2)*T,(b.y+3)*T,2,(b.h-6)*T);X.fillRect((b.x+3)*T,(b.y+b.h/2)*T,(b.w-6)*T,2)}
for(let l of L)if(!l.got){let col={ammo:"#e6d16a",armor:"#5bb0dd",medkit:"#ed6b72",rifle:"#e7a34c",smg:"#e7a34c",shotgun:"#e7a34c",grenade:"#b0c66e"}[l.type];X.fillStyle=col;X.fillRect(l.x-4,l.y-4,8,8)}
for(let v of V){X.fillStyle="#315a40";X.fillRect(v.x-18,v.y-9,36,18);X.fillStyle="#18231d";X.fillRect(v.x-12,v.y-7,9,5);X.fillRect(v.x+3,v.y-7,9,5)}
let o=P(M.objective),ex=P(M.extract);X.strokeStyle="#f1ca5d";X.lineWidth=3;X.beginPath();X.arc(o.x,o.y,15,0,7);X.stroke();X.fillStyle="#f1ca5d";X.font="900 7px system-ui";X.fillText("OBJETIVO",o.x-20,o.y+24);X.strokeStyle=M.done?"#65d9ff":"#738078";X.beginPath();X.arc(ex.x,ex.y,16,0,7);X.stroke();X.fillStyle="#65d9ff";X.fillText("EXTRACCIÓN",ex.x-24,ex.y+25);
for(let e of E)if(e.alive)soldier(e.x,e.y,true,p.x-e.x,p.y-e.y);for(let s of S){X.strokeStyle=s.enemy?"#ff6871":"#ffe16c";X.lineWidth=2;X.beginPath();X.moveTo(s.x,s.y);X.lineTo(s.x-s.dx*12,s.y-s.dy*12);X.stroke()}for(let g of G){X.fillStyle="#28352d";X.beginPath();X.arc(g.x,g.y,5,0,7);X.fill()}for(let f of F){f.t+=.02;X.globalAlpha=Math.max(0,1-f.t*1.5);X.strokeStyle=f.boom?"#ffd26a":"#edf4ee";X.beginPath();X.arc(f.x,f.y,8+f.t*80,0,7);X.stroke();X.globalAlpha=1}soldier(p.x,p.y,false,aim.x,aim.y);X.restore();mini()}
function mini(){MX.clearRect(0,0,244,164);MX.fillStyle="#2e442f";MX.fillRect(0,0,244,164);let sx=244/MW,sy=164/MH;for(let y=0;y<MH;y+=2)for(let x=0;x<MW;x+=2){MX.fillStyle=M.grid[y][x]=="#"?"#756a5e":M.grid[y][x]=="~"?"#4d8e99":"#4a663f";MX.fillRect(x*sx,y*sy,sx*2,sy*2)}MX.strokeStyle="#ead66b";MX.beginPath();MX.arc(122,82,zoneR/WW*244,0,7);MX.stroke();MX.fillStyle="#fff";MX.beginPath();MX.arc(p.x/WW*244,p.y/WH*164,3,0,7);MX.fill();for(let e of E)if(e.alive){MX.fillStyle="#e35460";MX.fillRect(e.x/WW*244-1,e.y/WH*164-1,3,3)}}
function loop(t){let dt=Math.min((t-last)/1000,.035);last=t;if(!won){stepPlayer(dt);p.cd=Math.max(0,p.cd-dt);if(hold)fire();updateHeal(dt);E.forEach(e=>ai(e,dt));shots(dt);gren(dt);zone(dt);objective();$("#prompt").style.display=L.some(l=>!l.got&&Math.hypot(l.x-p.x,l.y-p.y)<25)?"block":"none"}draw();requestAnimationFrame(loop)}
document.querySelectorAll(".gun").forEach(b=>b.onclick=()=>{weapon=b.dataset.w;p.ammo=gun[weapon].mag;document.querySelectorAll(".gun").forEach(x=>x.classList.toggle("sel",x===b));document.querySelector(".gun.sel span").textContent=p.ammo});$("#fire").onpointerdown=e=>{hold=true;fire()};$("#fire").onpointerup=$("#fire").onpointercancel=()=>hold=false;$("#gr").onclick=grenade;$("#heal").onclick=heal;$("#car").onclick=vehicle;$("#get").onclick=loot;$("#again").onclick=()=>load(M.id);$("#next").onclick=()=>{if(M.id<30)load(M.id+1)};
function pad(el,k,set,aiming){let drag=false;function u(e){let r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.36),y=(e.clientY-r.top-r.height/2)/(r.height*.36),m=Math.hypot(x,y);if(m>1){x/=m;y/=m}set({x,y});k.style.transform=`translate(${x*25}px,${y*25}px)`;if(aiming&&(x||y))aim={x,y}}el.onpointerdown=e=>{drag=true;el.setPointerCapture(e.pointerId);u(e)};el.onpointermove=e=>{if(drag)u(e)};el.onpointerup=el.onpointercancel=()=>{drag=false;set({x:0,y:0});k.style.transform="translate(0,0)"}}pad($("#jl"),$("#kl"),v=>move=v,false);pad($("#jr"),$("#kr"),v=>{},true);