const C=document.querySelector("#game"),X=C.getContext("2d"),MM=document.querySelector("#minimap"),MX=MM.getContext("2d"),$=s=>document.querySelector(s);
const TS=16,MW=128,MH=86;let maps=[],M,p,enemies=[],squad=[],loot=[],vehicles=[],shots=[],grenades=[],fx=[],last=0,won=false,zoneT=120,zoneR=620,weapon="rifle",fireHeld=false,move={x:0,y:0},aim={x:1,y:0},audio=null;
const guns={rifle:{mag:30,damage:34,rate:.16,range:360},smg:{mag:45,damage:20,rate:.09,range:260},shotgun:{mag:8,damage:72,rate:.65,range:155}};
fetch("levels.json").then(r=>r.json()).then(d=>{maps=d.maps;load(+localStorage.getItem("sombra_level")||1);requestAnimationFrame(loop)});
function pos(o){return{x:(o.x+.5)*TS,y:(o.y+.5)*TS}}function cell(x,y){return x>=0&&y>=0&&x<MW&&y<MH&&M.grid[y][x]=="."}function blocked(x,y){return !cell(Math.floor(x/TS),Math.floor(y/TS))}
function beep(f=440,d=.06,type="square",v=.035){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
function load(n){M=maps[Math.max(0,Math.min(199,n-1))];let s=pos(M.start);p={x:s.x,y:s.y,hp:100,ammo:30,grenades:3,cd:0,medic:0,inVehicle:false,kills:0,armor:0};enemies=M.enemies.map((e,i)=>{let q=pos(e);return{x:q.x,y:q.y,hp:100,alive:true,alert:false,cd:Math.random(),id:i}});loot=M.loot.map((l,i)=>({...pos(l),type:l.type,got:false,id:i}));vehicles=M.vehicles.map((v,i)=>({...pos(v),used:false,id:i}));let roles=[["ALFA","FUSILERO"],["BRAVO","FRANCO"],["CHARLIE","MÉDICO"],["DELTA","EXPLORADOR"]];squad=roles.map((r,i)=>({name:r[0],role:r[1],hp:100,alive:true,x:s.x+(i-1.5)*18,y:s.y+24}));shots=[];grenades=[];fx=[];won=false;zoneT=120;zoneR=620;weapon="rifle";fireHeld=false;document.querySelectorAll(".gun").forEach((b,i)=>b.classList.toggle("sel",i===0));$("#mn").textContent=String(M.id).padStart(3,"0");$("#hp").textContent=100;$("#alive").textContent=enemies.length+1;$("#kills").textContent=0;$("#status")?.remove();renderSquad();beep(220,.08,"triangle")}
function renderSquad(){$("#squad").innerHTML=squad.map(o=>`<div class="op"><b>${o.name}</b>${o.role}<div class="bar"><i style="width:${o.hp}%"></i></div></div>`).join("")}
function movePlayer(dt){let sp=p.inVehicle?105:62,nx=p.x+move.x*sp*dt,ny=p.y+move.y*sp*dt;if(!blocked(nx,p.y))p.x=nx;if(!blocked(p.x,ny))p.y=ny}
function shoot(){if(won||p.cd>0||p.ammo<=0)return;let g=guns[weapon];p.cd=g.rate;p.ammo--;$("#weapons .sel span").textContent=p.ammo;beep(weapon==="shotgun"?100:weapon==="smg"?180:240,.045,"square",.025);shots.push({x:p.x,y:p.y,dx:aim.x,dy:aim.y,range:g.range,damage:g.damage,enemy:false})}
function grenade(){if(p.grenades<=0)return;p.grenades--;let d=aim;grenades.push({x:p.x,y:p.y,tx:p.x+d.x*170,ty:p.y+d.y*170,t:0});beep(110,.1,"sawtooth")}
function nearestMedic(){return squad.find(o=>o.role==="MÉDICO"&&o.alive)}
function callMedic(){if(p.medic)return;let c=nearestMedic();if(!c)return;p.medic=1;c.heal=true;beep(500,.1,"triangle")}
function updateMedic(dt){let c=nearestMedic();if(!c)return;if(c.heal){let dx=p.x-c.x,dy=p.y-c.y,d=Math.hypot(dx,dy);if(d>20){c.x+=dx/d*78*dt;c.y+=dy/d*78*dt}else{c.heal=false;p.medic=2}}if(p.medic===2&&p.hp<100){p.hp=Math.min(100,p.hp+24*dt);$("#hp").textContent=Math.round(p.hp)}if(p.medic===2&&p.hp>=100){p.medic=0;beep(760,.08,"triangle")}}
function enemyAI(e,dt){if(!e.alive)return;let d=Math.hypot(p.x-e.x,p.y-e.y);if(d<310){e.alert=true;let dx=p.x-e.x,dy=p.y-e.y,m=Math.hypot(dx,dy)||1;if(d>105&&!blocked(e.x+dx/m*15,e.y+dy/m*15)){e.x+=dx/m*15*dt;e.y+=dy/m*15*dt}e.cd-=dt;if(d<275&&e.cd<=0){e.cd=1.15+Math.random()*.5;shots.push({x:e.x,y:e.y,dx:dx/m,dy:dy/m,range:300,damage:7,enemy:true})}}}
function updateShots(dt){for(let s of shots){s.x+=s.dx*720*dt;s.y+=s.dy*720*dt;s.range-=720*dt;if(s.range<=0||blocked(s.x,s.y))s.dead=true;if(!s.enemy){for(let e of enemies)if(e.alive&&Math.hypot(s.x-e.x,s.y-e.y)<13){e.hp-=s.damage;s.dead=true;if(e.hp<=0){e.alive=false;p.kills++;$("#kills").textContent=p.kills;beep(90,.1,"sawtooth");fx.push({x:e.x,y:e.y,t:0,type:"kill"})}break}}else if(Math.hypot(s.x-p.x,s.y-p.y)<12){let dmg=Math.max(2,s.damage-(p.armor?3:0));p.hp=Math.max(0,p.hp-dmg);$("#hp").textContent=Math.round(p.hp);s.dead=true;beep(65,.06,"sawtooth");if(p.hp<=0)end(false)}}shots=shots.filter(s=>!s.dead)}
function updateGrenades(dt){for(let g of grenades){g.t+=dt;if(g.t>.55){for(let e of enemies)if(e.alive&&Math.hypot(e.x-g.tx,e.y-g.ty)<82){e.hp-=95;if(e.hp<=0)e.alive=false}fx.push({x:g.tx,y:g.ty,t:0,type:"boom"});beep(70,.16,"sawtooth");g.dead=true}}grenades=grenades.filter(g=>!g.dead)}
function pickup(){let l=loot.find(l=>!l.got&&Math.hypot(l.x-p.x,l.y-p.y)<28);if(!l)return; l.got=true;beep(700,.07,"triangle");if(l.type==="ammo")p.ammo=Math.min(90,p.ammo+20);if(l.type==="armor")p.armor=1;if(l.type==="medkit")p.hp=Math.min(100,p.hp+35);if(l.type==="grenade")p.grenades=Math.min(6,p.grenades+2);if(["rifle","smg","shotgun"].includes(l.type)){weapon=l.type;p.ammo=guns[weapon].mag;document.querySelectorAll(".gun").forEach(b=>b.classList.toggle("sel",b.dataset.w===weapon))}$("#pickup").style.display="none";$("#weapons .sel span").textContent=p.ammo}
function vehicle(){let v=vehicles.find(v=>Math.hypot(v.x-p.x,v.y-p.y)<32);if(!v)return;p.inVehicle=!p.inVehicle;beep(p.inVehicle?330:180,.1,"triangle")}
function updateZone(dt){zoneT-=dt;if(zoneT<=0){zoneT=120;zoneR=Math.max(210,zoneR-55)}let cx=MW*TS/2,cy=MH*TS/2,d=Math.hypot(p.x-cx,p.y-cy);if(d>zoneR){p.hp=Math.max(0,p.hp-5*dt);$("#hp").textContent=Math.round(p.hp);if(p.hp<=0)end(false)}let sec=Math.ceil(zoneT);$("#zt").textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`}
function objective(){let o=pos(M.objective),e=pos(M.extract);if(!M.done&&Math.hypot(p.x-o.x,p.y-o.y)<30){M.done=true;beep(800,.15,"triangle");$("#zone").textContent="🎯 OBJETIVO COMPLETADO · BUSCA EXTRACCIÓN"}if(M.done&&!won&&Math.hypot(p.x-e.x,p.y-e.y)<32)end(true)}
function end(ok){if(won)return;won=ok;$("#modal").style.display="grid";$("#mt").textContent=ok?"VICTORIA":"EL ESCUADRÓN FUE ELIMINADO";$("#mm").textContent=ok?`${M.name} · ${p.kills} bajas · extracción asegurada.`:"La operación terminó. Reintenta la zona.";if(ok&&M.id<200)localStorage.setItem("sombra_level",M.id+1);beep(ok?900:80,.25,ok?"triangle":"sawtooth")}
function camera(){let vw=C.width/1.5,vh=C.height/1.5;return{x:Math.max(0,Math.min(p.x-vw/2,MW*TS-vw)),y:Math.max(0,Math.min(p.y-vh/2,MH*TS-vh)),w:vw,h:vh}}
function draw(){X.clearRect(0,0,C.width,C.height);let cam=camera(),sc=1.5;X.save();X.scale(sc,sc);X.translate(-cam.x,-cam.y);for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){X.fillStyle=M.grid[y][x]==="#"?"#1f2922":((x+y)%2?"#3b4b35":"#42543b");X.fillRect(x*TS,y*TS,TS,TS)}
for(let b of M.buildings){X.strokeStyle="#9aafa0";X.lineWidth=2;X.strokeRect(b.x*TS+1,b.y*TS+1,b.w*TS-2,b.h*TS-2);X.fillStyle="#28352c";X.fillRect(b.x*TS+3,b.y*TS+3,b.w*TS-6,b.h*TS-6);X.strokeStyle="#68796f";X.strokeRect(b.x*TS+5,b.y*TS+5,b.w*TS-10,b.h*TS-10)}
for(let c of M.covers){X.fillStyle="#59665d";X.fillRect(c.x*TS+2,c.y*TS+2,TS-4,TS-4)}
for(let l of loot)if(!l.got){let col={ammo:"#e6d16b",armor:"#62a8d6",medkit:"#e86b70",rifle:"#e7a94f",smg:"#e7a94f",shotgun:"#e7a94f",grenade:"#a9b46b"}[l.type]||"#fff";X.fillStyle=col;X.fillRect(l.x-5,l.y-5,10,10);X.strokeStyle="#fff9";X.strokeRect(l.x-7,l.y-7,14,14)}
for(let d of M.drops){X.fillStyle="#b93442";X.fillRect(d.x*TS-8,d.y*TS-8,16,16);X.strokeStyle="#ff7c6e";X.strokeRect(d.x*TS-11,d.y*TS-11,22,22)}
for(let v of vehicles){X.save();X.translate(v.x,v.y);X.fillStyle="#2d5140";X.fillRect(-17,-9,34,18);X.fillStyle="#111817";X.fillRect(-12,-7,9,5);X.fillRect(3,-7,9,5);X.restore()}
let o=pos(M.objective),ex=pos(M.extract);X.beginPath();X.arc(o.x,o.y,16,0,7);X.strokeStyle="#f1c85c";X.lineWidth=3;X.stroke();X.fillStyle="#f1c85c";X.font="900 7px system-ui";X.fillText("OBJETIVO",o.x-20,o.y+25);X.beginPath();X.arc(ex.x,ex.y,17,0,7);X.strokeStyle=M.done?"#69d8ff":"#64736d";X.stroke();X.fillStyle="#69d8ff";X.fillText("EXTRACCIÓN",ex.x-25,ex.y+27);
for(let e of enemies)if(e.alive){X.save();X.translate(e.x,e.y);X.fillStyle=e.alert?"#e34e5e":"#b54350";X.fillRect(-7,-7,14,14);X.fillStyle="#2b171a";X.fillRect(-5,-11,10,6);X.strokeStyle="#ffd6d6";X.strokeRect(-7,-7,14,14);X.restore()}
for(let s of squad)if(s.alive){X.save();X.translate(s.x,s.y);X.fillStyle=s.role==="MÉDICO"?"#6bc39e":"#557a65";X.fillRect(-8,-7,16,14);X.fillStyle="#dce5df";X.beginPath();X.arc(0,-9,5,0,7);X.fill();X.fillStyle="#1b2923";X.fillRect(-7,-4,14,3);X.restore()}
for(let s of shots){X.strokeStyle=s.enemy?"#ff6670":"#ffe16f";X.lineWidth=2;X.beginPath();X.moveTo(s.x,s.y);X.lineTo(s.x-s.dx*13,s.y-s.dy*13);X.stroke()}
for(let g of grenades){X.fillStyle="#303c34";X.beginPath();X.arc(g.x,g.y,5,0,7);X.fill()}
for(let f of fx){f.t+=.02;X.globalAlpha=Math.max(0,1-f.t*1.7);X.beginPath();X.arc(f.x,f.y,8+f.t*85,0,7);X.strokeStyle=f.type==="boom"?"#ffd06a":"#e6f0ec";X.stroke();X.globalAlpha=1}
X.beginPath();X.arc(p.x,p.y,12,0,7);X.fillStyle="#eaf2ed";X.fill();X.strokeStyle="#66d2ae";X.lineWidth=3;X.stroke();X.beginPath();X.moveTo(p.x,p.y);X.lineTo(p.x+aim.x*25,p.y+aim.y*25);X.strokeStyle="#f1f6f2";X.stroke();X.restore();drawMini(cam)}
function drawMini(cam){MX.clearRect(0,0,230,160);MX.fillStyle="#263329";MX.fillRect(0,0,230,160);let sx=230/MW,sy=160/MH;for(let y=0;y<MH;y+=2)for(let x=0;x<MW;x+=2){MX.fillStyle=M.grid[y][x]=="#"?"#68736b":"#344638";MX.fillRect(x*sx,y*sy,sx*2,sy*2)}let cx=MW*TS/2,cy=MH*TS/2;MX.strokeStyle="#d5c36b";MX.beginPath();MX.arc(cx/MW/TS*230,cy/MH/TS*160,zoneR/(MW*TS)*230,0,7);MX.stroke();MX.fillStyle="#fff";MX.beginPath();MX.arc(p.x/(MW*TS)*230,p.y/(MH*TS)*160,3,0,7);MX.fill();for(let e of enemies)if(e.alive){MX.fillStyle="#e04f5c";MX.fillRect(e.x/(MW*TS)*230-1,e.y/(MH*TS)*160-1,3,3)}}
function loop(t){let dt=Math.min((t-last)/1000,.035);last=t;if(!won){movePlayer(dt);p.cd=Math.max(0,p.cd-dt);if(fireHeld)shoot();updateMedic(dt);enemies.forEach(e=>enemyAI(e,dt));updateShots(dt);updateGrenades(dt);updateZone(dt);objective();let l=loot.find(l=>!l.got&&Math.hypot(l.x-p.x,l.y-p.y)<28);$("#pickup").style.display=l?"block":"none";}draw();requestAnimationFrame(loop)}
document.querySelectorAll(".gun").forEach(b=>b.onclick=()=>{weapon=b.dataset.w;p.ammo=guns[weapon].mag;document.querySelectorAll(".gun").forEach(x=>x.classList.toggle("sel",x===b));$("#weapons .sel span").textContent=p.ammo;beep(420,.05,"triangle")});
$("#fire").onpointerdown=e=>{e.preventDefault();fireHeld=true;if(!audio)beep(250,.02);};$("#fire").onpointerup=$("#fire").onpointercancel=()=>fireHeld=false;$("#grenade").onclick=grenade;$("#medic").onclick=callMedic;$("#enter").onclick=vehicle;$("#loot").onclick=pickup;$("#retry").onclick=()=>load(M.id);$("#next").onclick=()=>{if(M.id<200)load(M.id+1)};
function pad(el,knob,set,aiming=false){let drag=false;function upd(e){let r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.36),y=(e.clientY-r.top-r.height/2)/(r.height*.36),m=Math.hypot(x,y);if(m>1){x/=m;y/=m}set({x,y});knob.style.transform=`translate(${x*25}px,${y*25}px)`;if(aiming&&(x||y))aim={x,y}}el.onpointerdown=e=>{drag=true;el.setPointerCapture(e.pointerId);upd(e)};el.onpointermove=e=>{if(drag)upd(e)};el.onpointerup=el.onpointercancel=()=>{drag=false;set({x:0,y:0});knob.style.transform="translate(0,0)"}}pad($("#leftJoy"),$("#lk"),v=>move=v);pad($("#aimPad"),$("#ak"),v=>{},true);
document.addEventListener("keydown",e=>{if(e.key==="g")grenade();if(e.key==="h")callMedic();if(e.key==="e")vehicle();if(e.key==="f")pickup();if(e.key==="1")document.querySelector('[data-w="rifle"]').click();if(e.key==="2")document.querySelector('[data-w="smg"]').click();if(e.key==="3")document.querySelector('[data-w="shotgun"]').click()});